// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBeRhfdrIYgVdwOQPaE4KB8z0sRTLVgpsk',
    appId: '1:901200470447:web:6092599e0cccc4e6114f5a',
    messagingSenderId: '901200470447',
    projectId: 'ditonton-87eff',
    authDomain: 'ditonton-87eff.firebaseapp.com',
    storageBucket: 'ditonton-87eff.appspot.com',
    measurementId: 'G-E2J0PRTGQR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3eDOS1xsbwQWZy1Sg5i5PngGW6HyNBO8',
    appId: '1:901200470447:android:73b0006b0157d32b114f5a',
    messagingSenderId: '901200470447',
    projectId: 'ditonton-87eff',
    storageBucket: 'ditonton-87eff.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYbYh9V_8bR7Je-eI6UFHwD_WHOBjitm8',
    appId: '1:901200470447:ios:0872eb5852899048114f5a',
    messagingSenderId: '901200470447',
    projectId: 'ditonton-87eff',
    storageBucket: 'ditonton-87eff.appspot.com',
    iosClientId:
        '901200470447-3mcih3hpe3rl3ih7p23bufbhv647s52d.apps.googleusercontent.com',
    iosBundleId: 'com.dicoding.ditonton',
  );
}
