// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCuEl1s0qKruvdsnzdidTZesahK35_gesk',
    appId: '1:709499197487:web:e5450a8ea2096a79e40eda',
    messagingSenderId: '709499197487',
    projectId: 'ditonton-cca14',
    authDomain: 'ditonton-cca14.firebaseapp.com',
    storageBucket: 'ditonton-cca14.appspot.com',
    measurementId: 'G-RNBG994N22',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDF6mcdKJmah-vJ8g9jzRH7HLo4R19nEIE',
    appId: '1:709499197487:android:69131187db9a24dee40eda',
    messagingSenderId: '709499197487',
    projectId: 'ditonton-cca14',
    storageBucket: 'ditonton-cca14.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBta3-XJ4Pc4a1EunVYNbMmPOq8PXBD7b8',
    appId: '1:709499197487:ios:603a8a587ea76fc1e40eda',
    messagingSenderId: '709499197487',
    projectId: 'ditonton-cca14',
    storageBucket: 'ditonton-cca14.appspot.com',
    iosClientId: '709499197487-9kt6qnnqrfmkmnjqar74vkr5c9p0tbp1.apps.googleusercontent.com',
    iosBundleId: 'com.dicoding.ditonton',
  );
}
